CLASS ztest_i330017 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ztest_i330017 IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
    out->write('Hello ABAP Git!').
  ENDMETHOD.
ENDCLASS.
